### ISSUE TITLE
shift to tidyverse?

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#101]
Something I am aware of but too ignorant to know about is that there are accepted ways of building new plot types in R that build on ggplot2. My bet is that we *don't* do this right yet, but that we probably *should* for RWTY2. 

Related to this, we could consider shifting to a tidyverse format for the whole of RWTY2. If we did this we could leverage packages like this:
https://mjskay.github.io/tidybayes/

**Comment by danlwarren** [comment]
Absolutely agreed.  We should look into using treeplyr too; Luke Harmon showed it off at our Evolution workshop this year and it seemed incredibly useful.

**Comment by roblanf** [comment]
closing because we've decided to keep a lot of things how they were. There is no material benefit to going through everything and making it tidyverse. Conversely there's a lot of scope that we'd introduce all sorts of interesting bugs.
