### ISSUE TITLE
standardise name of LnL column in p table

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#116]
it's useful to have this standardised in our internal parameter tables. 

Suggestion: we use the MrBayes terminology and always call the liklihood column 'LnL'

For each input file format in load.trees, we now need to specify the names of the likelihood colum and rename it in the ptable. In part this is necessary to do things like calculate the burnin in https://github.com/danlwarren/RWTY/issues/98

**Comment by roblanf** [comment]
So here's the information:

MrBayes:
* 'LnL' = 'LnL'

*BEAST:
* 'LnL' = 'likelihood'

BEAST:
* 'LnL' = 'likelihood'

RevBayes:
* 'LnL' = 'Likelihood'

**Comment by danlwarren** [comment]
Done for now as far as I know, but I don't have any sample files to try it on.
