### ISSUE TITLE
add a burnin plot

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#117]
the same as the likelihood parameter plot, except it's all samples.

Burnin for each chain is marked with a solid blue vertical line
Burnin for the analyses (which is the max of all burnins) is marked with a dashed red line

This will allow users to easily see if their chains have crazy different burnins, and then they can decide what to do about that.

**Comment by danlwarren** [comment]
This has been added and is now on develop.  I used the autocorr plots instead of likelihood because the burnin is more related to the autocorr plots, but if we want to do it with likelihoods instead that's fine.
