### ISSUE TITLE
analyze.multi plots

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#16]
In general, I am a bit lost on the output from analyze.multi.

Do we really just want to spit out four separate analyses on each chain. For minimal effort, we could take each of the plots from those chains, and put them together into a multi-faceted plot. This is important, since the whole point of looking at multiple chains is to check that they're doing roughly the same thing.

We should also be doing the same with the data, right?

So, for my money, we should be doing something like this. 

1. Run analyse.single on each chain
2. Combine each dataset from the chains together, adding a column for the chain ID, e.g. 'chain'
3. Creating plots with facet_wrap(~chain).

One big benefit of this is that we can make the output object of analyze.multi practically identical (in labels etc) to that from analyze.single. Indeed, this should be an aim. That will help users a lot, since they will always access the objects they are interested in with the same commands. 

The downside is that with lots of chains it can get clunky to automate how we choose a good number of rows in the facet_wrap(). For the treespace plots, I just go for a roughly square plot like this:

            facet_wrap(~chain, nrow=round(sqrt(length(unique(points$chain)))))    

We could (probably should) also allow users to set the number of rows in the plot (and check that their setting is not larger than the number of chains they have input).

**Comment by danlwarren** [comment]
I think this is pretty much done now, right?
