### ISSUE TITLE
allow users to pass in folder as input argument

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#18]
Can we do this? So a user could put in an input folder, and we would just look for files we recognise, like MrBayes .t and .p files.

To a limited extent, we already do this when we find .p files associated with input .t files. But it would be way cooler if we could just find all the .t files first. 

The output of this function would be a list of chains. We could then check this list for consistency (e.g. all chains the same length, same generation sampling, etc).

**Comment by danlwarren** [comment]
Rather than do this with a folder I've created a "load.multi" function that accepts a path and a set of regular expressions for tree and log files.  Seems to be working quite nicely.
