### ISSUE TITLE
makeplot.treespace -> `panel.margin` is deprecated. Please use `panel.spacing` property instead

### ISSUE THREAD

**Issue by pwkooij** [danlwarren/RWTY#181]
When using the makeplot.treespace() function I get the following warning messages:
```
> test.treespace.reduced = makeplot.treespace(my.trees.reduced[1:2], burnin = 206, n.points = 200, fill.color = "lnLike")
[1] "Creating treespace plots"
Warning messages:
1: `panel.margin` is deprecated. Please use `panel.spacing` property instead 
2: `panel.margin` is deprecated. Please use `panel.spacing` property instead 
```

This is probably something that needs to be adjusted in the code of the function

**Comment by danlwarren** [comment]
We will deal with this eventually, but as it doesn't affect outputs at all it's nothing to worry about.

**Comment by pwkooij** [comment]
Fair enough, just thought it was worth mentioning, as I didn't find any open or closed tickets with this.
