### ISSUE TITLE
more info on discordance metric

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#21]
Where does this metric come from?

More specifically, why are we using this metric and not the standard deviation of split frequencies? The latter has been in use for many years, and pretty much everyone in the field understands it almost intrinsically.

If the discordance metric has demonstrably better properties than the ASDSF (average standard deviation of split frequencies), that's great. But we do need to know them and spell them out. We also need to know the mathematical relationship between the two measures. As far as I can tell they are measuring almost exactly the same thing.

**Comment by roblanf** [comment]
OK, so @geneva gave me a formula for the discordance metric, 

![unnamed](https://cloud.githubusercontent.com/assets/895251/7465703/cec25d7e-f318-11e4-9a5d-c7fd7ffdf882.jpg)

Based on that, I wrote a little script to calculate that and the ASDSF for lots of datasets (pasted below). Really all this proves is that the discordance metric is just ASDSF divided by root two. 

![rplot](https://cloud.githubusercontent.com/assets/895251/7465720/5e0cff98-f319-11e4-867c-aa2df8293d64.jpg)

This presumably sorts itself out with some algebra if you compare the two formulas. 

So, assuming this is right, I propose dropping discordance, and just using ASDSF, for these reasons:

1. Most importantly, ASDSF is defined for any number of chains. Discordance is defined only for pairs of chains.
1. Both metrics have essentially the same properties. The only thing I prefer about discordance is that it has a nicer maximum bound (1). ASDSF has a maximum bound of 0.707 for two chains, and this reduces as you get more chains. However, I don't think that's enough of a reason to counter all the other reasons for using ASDSF, in particular because cases where we get even vaguely close to the maximum bound, and in particular cases where we actually care about interpreting the maximum bound, are vanishingly rare.
1. ASDSF is already widely used and understood. 

I'll leave this issue open until others have commented too, but unless I've gotten the sums wrong (quite possible), then I don't think we should be introducing any new metrics with RWTY, when the old metrics are arguably better.


'''
library(MASS)
set.seed(1111)

get.data <- function(n=100, sd){
	e1.sd <- sd #the standard deviation of the error term in the relationship y~a+b*x+e1
	e2.sd <- 10 #the standard deviation of the error term in the relationship z~c+d*y+e2
	
	e.cor <- matrix(c(1,0.3,0.3,1),2) #the correlation matrix of the two error terms (i.e. in this example they are correlated at r=0.3)
	e.cov <- e.cor*as.matrix(c(e1.sd,e2.sd))%*%t(as.matrix(c(e1.sd,e2.sd))) # the covariance matrix of the error terms
	e <- mvrnorm(n,c(0,0),e.cov) #generate the error terms givin the defined correlation
	e1 <- e[,1] #error term #1
	e2 <- e[,2] #error term #2
	x <- runif(n, min=0, max=1.0) #randomly generated x values
	a <- 0
	b <- 1
	y <- a + b*x + e1
	return(data.frame(x=x, y=y))
}

asdsf <- function(d){
	return(mean(apply(d,1,sd)))
}

disco <- function(d){	
	sum(abs(d$x - d$y))/nrow(d)
}


# simulate data at 100 different standard deviations
sds <- runif(1000)

asdsfs <- c()
discos <- c()
for(s in sds){
	
	d <- get.data(sd = s)
	asdsfs <- c(asdsfs, asdsf(d))
	discos <- c(discos, disco(d))
	
}

r <- data.frame('discordance' = discos, 'ASDSF' = asdsfs)

plot(r)

# a linear model proves the point
g = lm(r$discordance ~ r$ASDSF, -1)
summary(g)

# specificallly, discordance is just ASDSF divided by root 2
'''

**Comment by geneva** [comment]
I agree with all @roblanf 's points, particularly the multi-comparison capability of ASDSF. Sorry I didn't realize the direct relationship between these two measures previously.

**Comment by roblanf** [comment]
Hi @geneva, thanks for being so understanding! I was worried (still am a bit) that I was wrong, and that you would be offended.

So, if you think that I got this right, I suggest we just plug in the ASDSF in place of discordance, and use that for the phylo plot of chain similarity too. By the way, that plot of chain similarity is really cool.

I'll leave this open until we fix the issue.
