### ISSUE TITLE
*BEAST .log files do not load

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#22]
Here's an e.g. dataset: 

http://datadryad.org/bitstream/handle/10255/dryad.48536/AP_DRYAD.zip?sequence=1

If I load one of the .trees files with load.rwty(), it loads the trees fine. However, it fails to detect the associated .log files, which are nicely formatted and presumably could (should?) be read in automatically.

**Comment by danlwarren** [comment]
This should be fixed now, assuming the only difference between the .trees file name and the .log file name is the extension.  If not, users can always supply the log file path name to the load.trees function.
