### ISSUE TITLE
ditch 'labels'

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#24]
Right now we pass around a clunky kind of variable called 'labels'.

I suggest we ditch it. Instead, we can just tell users that we will automatically label their chains, but that if they want to specify their own labels they can just name the objects in the list of chains.

E.g. if you loaded 4 chains as t1, t2, t3, t4, you could do this:

```
# let RWTY label the chains in the order that they appear in the list
chains = list(t1, t2, t3, t4)

# name them yourself
chains = list('my first chain' = t1, 'my second chain' = t2, 'my third chain' = t3, 'my fourth chain' = t4)
```

Dropping the lables variable simplifies the user interface a lot.

**Comment by danlwarren** [comment]
Done.
