### ISSUE TITLE
check that all chains have the same taxa in the trees

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#29]
Take the first tree from each chain, and make sure that the taxa in all chains are identical.

**Comment by danlwarren** [comment]
Got this working now, using the function setequal() to compare the first tree from each chain.

**Comment by roblanf** [comment]
has a bug, so reopened it. Probably simple to fix. It is commented out for now (on the develop branch).

**Comment by danlwarren** [comment]
I'm not sure how that came back - I'd already fixed that error twice, but it got re-inserted in the merge somehow.  Maybe I failed to sync or something?

**Comment by danlwarren** [comment]
Oops, got it.  I had fixed it on master but not develop.
