### ISSUE TITLE
bug in analyze.multi

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#30]
```
data(fungus)
p = analyze.multi(list(run1, run1), burnin = 900, window.size = 10, treespace.points = 10)
```

gives this error:

```
Error in axis(side = side, at = x, labels = lab, ...) : 
  no locations are finite
```

Not sure why, but I suspect it's because if you pass identical chains (which folks occasionally will) then we get zero discordance, and our discordance tree doesn't work.

**Comment by danlwarren** [comment]
There's now a check to make sure that there is at least one non-zero discordance value.
