### ISSUE TITLE
Trouble finding utility functions

### ISSUE THREAD

**Issue by wrightaprilm** [danlwarren/RWTY#32]
Hi guys- 

When loading the package via library(RWTY), my install does not find the functions in rwty.utility. Manually importing them fixes the issue, but probably something to look into.

--a

**Comment by danlwarren** [comment]
I was just messing with this problem the other day, and I still haven't figured it out yet.  I'm sure it's something ridiculously simple, but I just can't find it.

**Comment by wrightaprilm** [comment]
I'm sure it is, but I don't know enough R to tell you.

Also, I'm poking around in treespace.R a touch - are the two panels of the plots made by plot_treespace on the same MDS? (i.e., can they be overlaid or must they be displayed separately)?

**Comment by danlwarren** [comment]
Rob's been doing that bit, but it's my understanding that they are the same.  I'll double check with him.

**Comment by wrightaprilm** [comment]
That's what it looked like, but figured I ought to check. More or less trying to make a TreeSetViz like plot without having to pay a color figure charge.

**Comment by danlwarren** [comment]
So when you were having the problem with utility functions, were you installing from the directory or from a .tar.gz file?  If the latter, I think I've got the one on the develop branch working.

**Comment by roblanf** [comment]
Hi @wrightaprilm, on the treespace thing. If you pass >1 chain to the plot.treespace function, then the plots are on the same MDS. I.e. one could in theory overlay them and colour the points differently (if you want to do this, get the xy coords from treespace.R and make your own plot. The idea is that if all your chains make roughly the same shapes in the points and heatmap plots, this is good. Doesn't guarantee convergence of course (but you never can, right) but does suggest they are all sampling from roughly the same distribution of trees.

**Comment by wrightaprilm** [comment]
@danlwarren I cloned the repo and then pointed the installer to the cloned folder. The cloned folder does contain the .tar.gz. I don't know enough about the default behavior of the package installer to know if it would use the already untarred folder or use the tar.

@roblanf Perfect. I uncovered kind of a cool result with partitionfinder morphology, which was that an unpartitioned and partitioned analyses tend to explore the same space, but the partitioned analysis will sample more heavily from the region containing the ML tree. So ... the run will go to islands of good solutions and tend to stay there, and ultimately more samples come from that region. I had already rewritten some plotting stuff in RWTY and added Phangorn's weighted RF function ... just wanted to make sure that in my quest to avoid a color figure fee, I wasn't doing something horrible, or super different from what TreeSet Viz does.

**Comment by danlwarren** [comment]
I believe this one is fixed on develop now, so I'm closing it.  It appears to be a roxygen deal, where it wasn't expoprting anything that didn't have documentation.  The utility functions weren't documented, so they were being chucked out.
