### ISSUE TITLE
example data objects

### ISSUE THREAD

**Issue by geneva** [danlwarren/RWTY#40]
`fungus.Rdata` is now a list of `rwty.trees` objects instead of containing multiple objects (eg, run1, run2). This arrangement breaks a bunch of the example code. We should either restore multiple objects in fungus.Rdata or update examples to call from within the fungus object, for example
``analyze.rwty(list(fungus$Fungus.Run1, fungus$Fungus.Run2),...``

**Comment by danlwarren** [comment]
Yeah, I'll update examples.  We don't even have to do the list() in the example code, just analyze.rwty(fungus).

**Comment by danlwarren** [comment]
Done!
