### ISSUE TITLE
Need to take care of minor stuff to get "R CMD check" happy

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/RWTY#42]
Although everything's working beautifully now, if you run "R CMD check" on the package it barfs a few warnings and notes.  None of them are serious issues, but CRAN won't take the package unless they're fixed.  I'll drop a log file into the Slack channel.

**Comment by roblanf** [comment]
see what happens now I've dropped GGally.

I see that we still get some things about importing things one by one instead of whole packages. I don't know how to do that in R but it seems sensible to import functions not whole pacakges.
