### ISSUE TITLE
Need to replace ggally_cor_modified somehow

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/RWTY#44]
I've been chasing down errors all day, and the only one left is with ggally_cor_modified and how it's called.  It's generating the following issues:

"Found the following possibly unsafe calls:
File ‘rwty/R/compare.n.R’:
  assignInNamespace("ggally_cor", ggally_cor, "GGally")"

And later with the test code checks:

"Error in get("asdsf.min", envir = globalenv()) : 
  object 'asdsf.min' not found"

Since all this is doing is calculating correlations and ASDF and returning a ggplot2 object, is there some way we can do that with a more purpose-built function that won't involve all of the namespace hacks?

**Comment by roblanf** [comment]
Some ideas here:

http://rstudio-pubs-static.s3.amazonaws.com/2852_379274d7c5734f979e106dcf019ec46c.html

We could build each correlation plot individually, and stitch them together. I.e. stop using Ggally alltogether. Not sure this is the right solution though.

**Comment by danlwarren** [comment]
There's another issue with the way we're doing scatter plot matrices, btw; every additional panel takes longer and longer to plot for some reason.  If you do a data set with a bunch of chains, the first few panels pop up immediately but then they get slower and slower.  If you do enough chains, you can end up waiting 15 minutes just for the scatter plot to finish drawing.  IDK if other methods would be faster, but as it stands it seems a little wonky to use.

**Comment by roblanf** [comment]
I agree. I'm a bit suspicious of ggally on this front.

I would suggest splitting this out as a few different functions: 

1. A scatter plot function to make the individual plots
2. A function to generate text in the matching panel for the above-diagonal (nb: you should just do this as an empty ggplot2 plot - no points but text)
3. A function to stitch it all together, maybe using multiplot or one of the solutions on that website

**Comment by geneva** [comment]
@danlwarren is right... all the namespace tomfoolery is just to force Ggally to generate what I wanted it to.  I have no special love for Ggally and will try to put something together with the framework @roblanf laid out above.

**Comment by roblanf** [comment]
Done. I have fixed this in the feature/facet-plots branch. I use base graphics, because I really couldn't see a way through the horrible namespace cludge. It's just not OK to screw with namespaces. Also, despite previous efforts the ggally pairs plot still had terrible axis labels, and also appears to have a bug that makes it take forever to plot. Very odd. 

In any case, the base graphics solution fixes all of this. It should also open the way for us to submit to CRAN I think.
