### ISSUE TITLE
Need to trim example data even further

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/RWTY#45]
Now that we've got two example data sets, they need to be shrunk down even more.  CRAN prefers packages to be under 5 MB, and we're currently at about 8.6.

**Comment by roblanf** [comment]
Cut the fungus data in half by trimming the last 50% of samples?

**Comment by roblanf** [comment]
Or, re-run it after removing half the taxa?

**Comment by danlwarren** [comment]
Nah, I'll just subsample at coarser intervals.

**Comment by roblanf** [comment]
right. Now I want to delete my obviously ill-thought-out suggestions.

**Comment by danlwarren** [comment]
Done.
