### ISSUE TITLE
Possibility of parallelizing rwty code? 

### ISSUE THREAD

**Issue by NickCrouch** [danlwarren/RWTY#46]
For example, in the function `tree.ess` when calculating topological ESS, would it be possible to have the option to use `mclapply`? This may improve run times for very large data sets

Nick

**Comment by roblanf** [comment]
Definitely possible. I have the code already. Watch this space.

On 22 June 2015 at 21:15, NickCrouch <notifications@github.com> wrote:

> For example, in the function tree.ess when calculating topological ESS,
> would it be possible to have the option to use mclapply? This may improve
> run times for very large data sets
>
> Nick
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danlwarren/RWTY/issues/46>.
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by roblanf** [comment]
Hi @NickCrouch,

I think this is mostly done now. Wherever I can, I default to using all possible cores. Let me know if you find other places though, and I can fix them too. Thanks for the suggestion, and sorry for the, ahem, rather slow response!

Rob
