### ISSUE TITLE
Why not using already vectorized code?

### ISSUE THREAD

**Issue by KlausVigo** [danlwarren/RWTY#47]
The underlying function RF.dist of tree.dist.matrix is vectorized already, why not using it directly?
There is the possibility you run out memory, but it seems your implementations runs out of time first. 

Here are some timings for my machine:
> system.time(dm1 <- tree.dist.matrix(fungus$Fungus.Run1$trees[1:100]))
   user  system elapsed 
  7.718   0.072   7.752 
> system.time(dm2 <- RF.dist(fungus$Fungus.Run1$trees[1:100]))
   user  system elapsed 
  0.089   0.000   0.089 
> sum(abs(dm1 - as.matrix(dm2)))
[1] 0

Regards, 
Klaus

**Comment by roblanf** [comment]
Whoa. Thanks for the suggestion. I hadn't realised that RF.dist was already vectorised!

**Comment by roblanf** [comment]
In fact, I think I had seen you mention on another thread that you were intending to do that, and then I completely forgot about that.

**Comment by roblanf** [comment]
Done. Thanks @KlausVigo. 

https://github.com/danlwarren/RWTY/commit/5847aa315a76b867a2fab69053e211ae5d50459b

@danlwarren, you should merge these to master before you present this (if you have time). There shouldn't be any conflicts.

**Comment by danlwarren** [comment]
Goodness, that makes a huge difference!  Thanks @KlausVigo
