### ISSUE TITLE
analyze.multi needs to check all parameters without defaults

### ISSUE THREAD

**Issue by roblanf** [danlwarren/RWTY#5]
I run this:

analyze.multi(list(t1, t2), burnin = 1000)

then the function does a bunch of work before eventually realising that it needed a variable 'window.size' which I hadn't set. 

We should check such things at the top of the analyze.multi function, before doing any processing, and spit useful error messages. E.g., for each variable that is missing with no default, we should print it out, and also point users in the right direction for how to set it (as a naive user, I have zero idea how to set window size, and of course I could read the manual, but we could also repeat bits of the manual in the error messages, which is a very nice and kind thing to do).

**Comment by danlwarren** [comment]
Did basically this for analyze.simple.  There's now a function called rwty.params.check that hangs out in the analyze.simple file, containing checks for all run parameters.
