### ISSUE TITLE
Need to fix asdsf tree

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/RWTY#54]
As it stands, this is being produced completely differently from the other trees.  That's fine - at present I'm not aware of a good ggplot-ish tree plotting package.  However, the fact that this one auto-plots when it's drawn and then has to be re-grabbed back into an object is a bit freakish, and is making me have to do weird stuff in the readme.rmd file to try to suppress it.  @geneva, would you mind taking a stab at getting this to a point where it's not auto-plotting to the plots window?

**Comment by roblanf** [comment]
ggtree is a ggplot extension for plotting trees, maybe useful here?
especially to get it in line with everything else in the pacakge

On 24 November 2015 at 15:31, Dan Warren <notifications@github.com> wrote:

> As it stands, this is being produced completely differently from the other
> trees. That's fine - at present I'm not aware of a good ggplot-ish tree
> plotting package. However, the fact that this one auto-plots when it's
> drawn and then has to be re-grabbed back into an object is a bit freakish,
> and is making me have to do weird stuff in the readme.rmd file to try to
> suppress it. @geneva <https://github.com/geneva>, would you mind taking a
> stab at getting this to a point where it's not auto-plotting to the plots
> window?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danlwarren/RWTY/issues/54>.
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by danlwarren** [comment]
I saw that on a web site, but when I tried to install it it says "not available for R 3.2.2".  Looks like it hasn't been updated in a while.

**Comment by fmichonneau** [comment]
ggtree is not in cran but in bioconductor.

**Comment by danlwarren** [comment]
Yeah it looks like it's on github too.  I'm not sure I want to put in a required package that's not on CRAN though.

**Comment by roblanf** [comment]
Totally agree. I think keeping all dependencies on CRAN is a really good
idea. As soon as you make installing even the tiniest bit of a pain in the
ass, you lose a huge number of users.

On 25 November 2015 at 06:01, Dan Warren <notifications@github.com> wrote:

> Yeah it looks like it's on github too. I'm not sure I want to put in a
> required package that's not on CRAN though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danlwarren/RWTY/issues/54#issuecomment-159373489>.
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by geneva** [comment]
I've got a solution that uses ggdendro which does for dendrograms what ggtree does for plot.phylo... but ggdendro is on CRAN.  Example results are below, the only thing I am still trying to fix is the left hand plotting. It seems like it should be trivial to make a right hand dendrogram plot, but so far, no luck. I can flip the y axis using scale_y_reverse() but the labels are still stuck on the left.  If it's not a deal breaker to anyone, I will push the modifications to include a left hand plot to rwty and continue to mess with flipping the y axis in the background.

![image](https://cloud.githubusercontent.com/assets/502133/11453804/91855f20-95e7-11e5-95c4-417f4706c292.png)

**Comment by roblanf** [comment]
done with ggdendro
