### ISSUE TITLE
Correlations and ASDSF printing weird in compare plots for large numbers of chains

### ISSUE THREAD

**Issue by danlwarren** [danlwarren/RWTY#55]
The axes and the stats for correlation coefficients and asdsfs are printing too large when we have more than about four chains.  

![image](https://cloud.githubusercontent.com/assets/3770891/11358357/07de14b2-92c5-11e5-8929-225ee15717b4.png)

We either need to scale the font or suppress printing for large numbers of chains.

**Comment by geneva** [comment]
Updated to correct this. New version adjusts text for ASDSF and Pearson correlation coeff. based on number of chains passed to analyze.rwty. Also, the compare.n function now uses chain names for datasets with 4 or fewer chains, and numbers for datasets with more than 4 chains.

4 chains:
![image](https://cloud.githubusercontent.com/assets/502133/11455593/4ed908ae-9635-11e5-84a0-b81b94e518f9.png)

 
>4 chains:
![image](https://cloud.githubusercontent.com/assets/502133/11455572/5b2586ec-9634-11e5-98b1-b5890805c116.png)
