### ISSUE TITLE
Possible bug in topological.approx.ess?

### ISSUE THREAD

**Issue by MichelleKendall** [danlwarren/RWTY#89]
Hi,

I've been getting some unexpected results out of topological.approx.ess. A (hopefully) reproducible example of this is from the README... it says that if you do
```
data("salamanders")
approx.ess <- topological.approx.ess(salamanders, burnin = 50)
```
you get
```
  operator approx.ess       chain
1        =   243.0683 AMOTL2.run1
2        =   134.2827 AMOTL2.run2
3        =   222.0624   LHX2.run1
4        =   251.0000   LHX2.run2
5        =   251.0000  TRMT5.run1
6        =   251.0000  TRMT5.run2
```

but I get
```
  operator approx.ess       chain
1        =        201 AMOTL2.run1
2        =        201 AMOTL2.run2
3        =        201   LHX2.run1
4        =        201   LHX2.run2
5        =        201  TRMT5.run1
6        =        201  TRMT5.run2
```
This is when running your current github version. Is it just me?!

Cheers,

Michelle

**Comment by danlwarren** [comment]
Yep, I'm definitely getting the same issue.  Hmmmmm.

**Comment by danlwarren** [comment]
Okay, I reckon it's something in the estimate.autocorr.m function.

**Comment by danlwarren** [comment]
Or not.  Actually all of the steps seem to be working fine when I drill down into it, as far as I can tell.  It produces reasonable results on the fungus data too (which is waaaaaayyyy more autocorrelated than the salamander data), so I'm wondering whether the screwup here is actually that something changed with the salamander data that we included in the CRAN version after that readme was made.  Rob @roblanf , do you recall whether we thinned that data more to make it CRAN-worthy?  That would explain it.

**Comment by roblanf** [comment]
No idea. But you could check by comparing the two files, right?

**Comment by danlwarren** [comment]
I went through this again yesterday and I'm pretty sure it's just that those chains have been subsampled so thinly and have so few trees that they're all pretty much independent.
